# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthDialog(object):
    def setupUi(self, AuthDialog):
        AuthDialog.setObjectName("AuthDialog")
        AuthDialog.resize(412, 285)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AuthDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(AuthDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelLogin = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelLogin.setFont(font)
        self.labelLogin.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLogin.setObjectName("labelLogin")
        self.verticalLayout_3.addWidget(self.labelLogin)
        self.lineEditLogin = QtWidgets.QLineEdit(self.tab)
        self.lineEditLogin.setObjectName("lineEditLogin")
        self.verticalLayout_3.addWidget(self.lineEditLogin)
        self.labelPassword = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelPassword.setFont(font)
        self.labelPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPassword.setObjectName("labelPassword")
        self.verticalLayout_3.addWidget(self.labelPassword)
        self.lineEditPassword = QtWidgets.QLineEdit(self.tab)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.verticalLayout_3.addWidget(self.lineEditPassword)
        self.checkBoxShowPassword = QtWidgets.QCheckBox(self.tab)
        self.checkBoxShowPassword.setObjectName("checkBoxShowPassword")
        self.verticalLayout_3.addWidget(self.checkBoxShowPassword)
        self.checkBoxSavePassword = QtWidgets.QCheckBox(self.tab)
        self.checkBoxSavePassword.setObjectName("checkBoxSavePassword")
        self.verticalLayout_3.addWidget(self.checkBoxSavePassword)
        self.pushButtonLogin = QtWidgets.QPushButton(self.tab)
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.verticalLayout_3.addWidget(self.pushButtonLogin)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelPassword_3 = QtWidgets.QLabel(self.tab_2)
        self.labelPassword_3.setObjectName("labelPassword_3")
        self.gridLayout.addWidget(self.labelPassword_3, 2, 0, 1, 1)
        self.lineEditLoginSignup = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditLoginSignup.setObjectName("lineEditLoginSignup")
        self.gridLayout.addWidget(self.lineEditLoginSignup, 0, 1, 1, 1)
        self.labelLogin_2 = QtWidgets.QLabel(self.tab_2)
        self.labelLogin_2.setObjectName("labelLogin_2")
        self.gridLayout.addWidget(self.labelLogin_2, 0, 0, 1, 1)
        self.labelPassword_2 = QtWidgets.QLabel(self.tab_2)
        self.labelPassword_2.setObjectName("labelPassword_2")
        self.gridLayout.addWidget(self.labelPassword_2, 1, 0, 1, 1)
        self.labelEmail = QtWidgets.QLabel(self.tab_2)
        self.labelEmail.setObjectName("labelEmail")
        self.gridLayout.addWidget(self.labelEmail, 3, 0, 1, 1)
        self.labelPhone = QtWidgets.QLabel(self.tab_2)
        self.labelPhone.setObjectName("labelPhone")
        self.gridLayout.addWidget(self.labelPhone, 4, 0, 1, 1)
        self.lineEditPasswordSignup = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditPasswordSignup.setClearButtonEnabled(False)
        self.lineEditPasswordSignup.setObjectName("lineEditPasswordSignup")
        self.gridLayout.addWidget(self.lineEditPasswordSignup, 1, 1, 1, 1)
        self.lineEditPasswordSignupRepeat = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditPasswordSignupRepeat.setObjectName("lineEditPasswordSignupRepeat")
        self.gridLayout.addWidget(self.lineEditPasswordSignupRepeat, 2, 1, 1, 1)
        self.lineEditEmail = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.gridLayout.addWidget(self.lineEditEmail, 3, 1, 1, 1)
        self.lineEditPhone = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.gridLayout.addWidget(self.lineEditPhone, 4, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.checkBoxShowPassworsSignup = QtWidgets.QCheckBox(self.tab_2)
        self.checkBoxShowPassworsSignup.setObjectName("checkBoxShowPassworsSignup")
        self.verticalLayout_4.addWidget(self.checkBoxShowPassworsSignup)
        self.pushButtonSignup = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonSignup.setObjectName("pushButtonSignup")
        self.verticalLayout_4.addWidget(self.pushButtonSignup)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(AuthDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AuthDialog)

    def retranslateUi(self, AuthDialog):
        _translate = QtCore.QCoreApplication.translate
        AuthDialog.setWindowTitle(_translate("AuthDialog", "Аутентификация"))
        self.labelLogin.setText(_translate("AuthDialog", "Логин"))
        self.labelPassword.setText(_translate("AuthDialog", "Пароль"))
        self.checkBoxShowPassword.setText(_translate("AuthDialog", "Показать пароль"))
        self.checkBoxSavePassword.setText(_translate("AuthDialog", "Сохранить пароль"))
        self.pushButtonLogin.setText(_translate("AuthDialog", "Войти"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("AuthDialog", "Войти"))
        self.labelPassword_3.setText(_translate("AuthDialog", "Повторите пароль"))
        self.labelLogin_2.setText(_translate("AuthDialog", "Логин"))
        self.labelPassword_2.setText(_translate("AuthDialog", "Пароль"))
        self.labelEmail.setText(_translate("AuthDialog", "Email"))
        self.labelPhone.setText(_translate("AuthDialog", "Телефон"))
        self.checkBoxShowPassworsSignup.setText(_translate("AuthDialog", "Показать пароль"))
        self.pushButtonSignup.setText(_translate("AuthDialog", "Зарегистрироваться"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("AuthDialog", "Зарегистрироваться"))


