# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profile_view.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfileView(object):
    def setupUi(self, ProfileView):
        ProfileView.setObjectName("ProfileView")
        ProfileView.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ProfileView)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBoxProfile = QtWidgets.QGroupBox(ProfileView)
        self.groupBoxProfile.setFlat(False)
        self.groupBoxProfile.setChecked(False)
        self.groupBoxProfile.setObjectName("groupBoxProfile")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxProfile)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_user = QtWidgets.QLineEdit(self.groupBoxProfile)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.gridLayout.addWidget(self.lineEdit_user, 0, 1, 1, 2)
        self.lineEdit_phone = QtWidgets.QLineEdit(self.groupBoxProfile)
        self.lineEdit_phone.setInputMask("+9 (999) 999-99-99; ")
        self.lineEdit_phone.setText("+ () --")
        self.lineEdit_phone.setCursorPosition(18)
        self.lineEdit_phone.setPlaceholderText("+7(000)000-0000")
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.gridLayout.addWidget(self.lineEdit_phone, 6, 1, 1, 2)
        self.lineEdit_last_name = QtWidgets.QLineEdit(self.groupBoxProfile)
        self.lineEdit_last_name.setObjectName("lineEdit_last_name")
        self.gridLayout.addWidget(self.lineEdit_last_name, 4, 1, 1, 2)
        self.radioButton_man = QtWidgets.QRadioButton(self.groupBoxProfile)
        self.radioButton_man.setChecked(False)
        self.radioButton_man.setAutoExclusive(True)
        self.radioButton_man.setObjectName("radioButton_man")
        self.gridLayout.addWidget(self.radioButton_man, 7, 1, 1, 1)
        self.label_first_name = QtWidgets.QLabel(self.groupBoxProfile)
        self.label_first_name.setToolTip("")
        self.label_first_name.setObjectName("label_first_name")
        self.gridLayout.addWidget(self.label_first_name, 3, 0, 1, 1)
        self.label_middle_name = QtWidgets.QLabel(self.groupBoxProfile)
        self.label_middle_name.setToolTip("")
        self.label_middle_name.setObjectName("label_middle_name")
        self.gridLayout.addWidget(self.label_middle_name, 5, 0, 1, 1)
        self.label_last_name = QtWidgets.QLabel(self.groupBoxProfile)
        self.label_last_name.setToolTip("")
        self.label_last_name.setObjectName("label_last_name")
        self.gridLayout.addWidget(self.label_last_name, 4, 0, 1, 1)
        self.label_user = QtWidgets.QLabel(self.groupBoxProfile)
        self.label_user.setObjectName("label_user")
        self.gridLayout.addWidget(self.label_user, 0, 0, 1, 1)
        self.label_phone = QtWidgets.QLabel(self.groupBoxProfile)
        self.label_phone.setObjectName("label_phone")
        self.gridLayout.addWidget(self.label_phone, 6, 0, 1, 1)
        self.dateEdit_birth_date = QtWidgets.QDateEdit(self.groupBoxProfile)
        self.dateEdit_birth_date.setObjectName("dateEdit_birth_date")
        self.gridLayout.addWidget(self.dateEdit_birth_date, 8, 2, 1, 1)
        self.label_gender = QtWidgets.QLabel(self.groupBoxProfile)
        self.label_gender.setObjectName("label_gender")
        self.gridLayout.addWidget(self.label_gender, 7, 0, 1, 1)
        self.label_birth_date = QtWidgets.QLabel(self.groupBoxProfile)
        self.label_birth_date.setObjectName("label_birth_date")
        self.gridLayout.addWidget(self.label_birth_date, 8, 0, 1, 1)
        self.lineEdit_middle_name = QtWidgets.QLineEdit(self.groupBoxProfile)
        self.lineEdit_middle_name.setObjectName("lineEdit_middle_name")
        self.gridLayout.addWidget(self.lineEdit_middle_name, 5, 1, 1, 2)
        self.radioButton_woman = QtWidgets.QRadioButton(self.groupBoxProfile)
        self.radioButton_woman.setChecked(False)
        self.radioButton_woman.setAutoExclusive(True)
        self.radioButton_woman.setObjectName("radioButton_woman")
        self.gridLayout.addWidget(self.radioButton_woman, 7, 2, 1, 1)
        self.lineEdit_first_name = QtWidgets.QLineEdit(self.groupBoxProfile)
        self.lineEdit_first_name.setObjectName("lineEdit_first_name")
        self.gridLayout.addWidget(self.lineEdit_first_name, 3, 1, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.pushButton_save_profile = QtWidgets.QPushButton(self.groupBoxProfile)
        self.pushButton_save_profile.setObjectName("pushButton_save_profile")
        self.verticalLayout_3.addWidget(self.pushButton_save_profile)
        self.verticalLayout_2.addWidget(self.groupBoxProfile)

        self.retranslateUi(ProfileView)
        QtCore.QMetaObject.connectSlotsByName(ProfileView)

    def retranslateUi(self, ProfileView):
        _translate = QtCore.QCoreApplication.translate
        ProfileView.setWindowTitle(_translate("ProfileView", "Form"))
        self.groupBoxProfile.setTitle(_translate("ProfileView", "Профиль пользователя"))
        self.lineEdit_user.setToolTip(_translate("ProfileView", "Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_."))
        self.lineEdit_phone.setToolTip(_translate("ProfileView", "Введите ваш номер телефона"))
        self.lineEdit_last_name.setToolTip(_translate("ProfileView", "Введите вашу фамилию"))
        self.radioButton_man.setToolTip(_translate("ProfileView", "Выберите один из пунктов"))
        self.radioButton_man.setText(_translate("ProfileView", "Мужской"))
        self.label_first_name.setText(_translate("ProfileView", "Имя"))
        self.label_middle_name.setText(_translate("ProfileView", "Отчество"))
        self.label_last_name.setText(_translate("ProfileView", "Фамилия"))
        self.label_user.setText(_translate("ProfileView", "Логин"))
        self.label_phone.setText(_translate("ProfileView", "Телефон"))
        self.dateEdit_birth_date.setToolTip(_translate("ProfileView", "Введите дату вашего рождения"))
        self.label_gender.setText(_translate("ProfileView", "Пол"))
        self.label_birth_date.setText(_translate("ProfileView", "Дата рождения"))
        self.lineEdit_middle_name.setToolTip(_translate("ProfileView", "Введите ваше отчество"))
        self.radioButton_woman.setToolTip(_translate("ProfileView", "Выберите один из пунктов"))
        self.radioButton_woman.setText(_translate("ProfileView", "Женский"))
        self.lineEdit_first_name.setToolTip(_translate("ProfileView", "Введите ваше имя"))
        self.pushButton_save_profile.setText(_translate("ProfileView", "Сохранить профиль"))


